// Comprehensive Brand & Note Normalizer
// Handles case unification, composite star+brand separation, and spelling corrections.

const exactMap = {
  '（泰国）MARIMEKKO': ['MARIMEKKO', '泰国'],
  'BV郭佩奇': ['BV', '郭佩奇'],
  '（李一桐）VIAPITTI': ['VIAPITTI', '李一桐'],
  '（扣子鞋）帕拉丁': ['帕拉丁', '扣子鞋'],
  '（时代少年团）soapopera': ['soapopera', '时代少年团'],
  '（韩国女团）soapopera': ['soapopera', '韩国女团'],
  '（孙怡饰品）star jewelry': ['star jewelry', '孙怡饰品'],
  '（王楚然）VIAPITTI': ['VIAPITTI', '王楚然'],
  '董洁（stella luna）': ['stella luna', '董洁'],
  '王一博（安踏）': ['安踏', '王一博'],
  '罗一舟（RUDSAK）': ['RUDSAK', '罗一舟'],
  '周雨彤（crocs）': ['crocs', '周雨彤'],
  '豆豆思加图': ['思加图', '豆豆'],
  '赵露思melissa': ['melissa', '赵露思'],
  '金晨（lost in）': ['lost in', '金晨'],
  '赵露思（真美诗）': ['真美诗', '赵露思'],
  '关晓彤（ROSEONLY）': ['ROSEONLY', '关晓彤'],
  '郭晓婷（VAA）': ['VAA', '郭晓婷'],
  '王玉雯（lost in）': ['lost in', '王玉雯'],
  '喻言（sinsin）': ['sinsin', '喻言'],
  '卢婧姗（太平鸟）': ['太平鸟', '卢婧姗'],
  '董洁（思加图）': ['思加图', '董洁'],
  '真美诗（合集）': ['真美诗', '合集'],
  '宋佳songmont': ['songmont', '宋佳'],
  'SU（孔雪儿）': ['SU', '孔雪儿'],
  'su高叶': ['SU', '高叶'],
  '董洁（ACMEITEM）': ['ACMEITEM', '董洁'],
  'ORG(时代少年团)': ['ORG', '时代少年团'],
  '骆驼防晒衣（张予曦）': ['骆驼', '张予曦 防晒衣'],
  'solif大包（mc jin）': ['solif', 'mc jin 大包'],
  '得物（短袖）': ['得物', '短袖'],
  'OMTO(于文文)': ['OMTO', '于文文'],
  'lost in(张新成)': ['lost in', '张新成'],
  'hunter(田曦薇雨靴)': ['hunter', '田曦薇 雨靴'],
  'lily（董璇）': ['lily', '董璇'],
  'AOJO眼镜': ['AOJO', '眼镜'],
  '阿娇柏瑞美防晒粉饼': ['柏瑞美', '阿娇 防晒粉饼'],
  '孙怡（ONCHIC）': ['ONCHIC', '孙怡'],
  '思加图董洁': ['思加图', '董洁'],
  '周也wanatry': ['wanatry', '周也'],
  '古良吉吉（张嘉倪）': ['古良吉吉', '张嘉倪'],
  '徐梦洁bagsmart': ['bagsmart', '徐梦洁'],
  '白鹿 marsper': ['marsper', '白鹿'],
  '钟楚曦李宁': ['李宁', '钟楚曦'],
  '赵今麦HEFANG': ['HEFANG', '赵今麦'],
  '檀健次vtvn': ['VAVN', '檀健次'],
  '得物（鞋子）': ['得物', '鞋子'],
  '侯明昊lilbetter': ['lilbetter', '侯明昊'],
  '欧阳娜娜(有兰)': ['有兰', '欧阳娜娜'],
  '白鹿（何方）': ['HEFANG', '白鹿'],
  '刘耀文（apm）': ['apm', '刘耀文'],
  '祝绪丹达芙妮': ['达芙妮', '祝绪丹'],
  '张极海昌': ['海昌', '张极'],
  '祝绪丹（tanni）': ['tanni', '祝绪丹'],
  '符雅凝(vavz)': ['vavz', '符雅凝'],
  '宋佳朗姿': ['朗姿', '宋佳'],
  '刘逸云 nautica': ['nautica', '刘逸云'],
  '徐海乔（爱颗米）': ['ACMEITEM', '徐海乔'],
  'baby红蜻蜓': ['红蜻蜓', 'baby'],
  '祝绪丹cafune': ['cafune', '祝绪丹'],
  '赵今麦wanatry': ['wanatry', '赵今麦'],
  '张淼怡太平鸟': ['太平鸟', '张淼怡'],
  '董洁真美诗': ['真美诗', '董洁'],
  '董洁何方': ['HEFANG', '董洁'],
  '金晨真美诗': ['真美诗', '金晨'],
  '白鹿wanatry': ['wanatry', '白鹿'],
  'baby  vwl': ['vwl', 'baby'],
  '真美诗合集': ['真美诗', '合集'],
  '戚薇VAVN': ['VAVN', '戚薇'],
  '张小斐真美诗': ['真美诗', '张小斐'],
  '秦岚 toryburch': ['toryburch', '秦岚'],
  '邓为marid': ['MARDI', '邓为'],
  '马天宇unicahomme': ['unicahomme', '马天宇'],
  'maje包包': ['maje', '包包'],
  '周迅duvetica': ['DUVETICA', '周迅'],
  '陈粒as dalio': ['as dalio', '陈粒'],
  '王阳TRETOTN': ['TRETOTN', '王阳'],
  '小香风wana try': ['wanatry', '小香风'],
  '黄子韬（得物）': ['得物', '黄子韬'],
  '韩素希（fila）': ['FILA', '韩素希'],
  'MLB液态银鞋子': ['MLB', '液态银鞋子'],
  '肖战（mackage）': ['mackage', '肖战'],
  '思加图（杨幂）': ['思加图', '杨幂'],
  '陈钰琪（wanatry）': ['wanatry', '陈钰琪'],
  '向涵之（wussa）': ['wussa', '向涵之'],
  '姜贞羽（wanatry）': ['wanatry', '姜贞羽'],
  '张柏芝（newbalance）': ['newbalance', '张柏芝'],
  '李一桐（JNBY）': ['JNBY', '李一桐'],
  '卢昱晓（何方）': ['HEFANG', '卢昱晓'],
  '王俊凯（champion）': ['champion', '王俊凯'],
  '田曦薇wanatry': ['wanatry', '田曦薇'],
  '董洁rabeanco': ['rabeanco', '董洁'],
  '李汶翰lifework': ['lifework', '李汶翰'],
  'lost in echo陈钰琪': ['lost in echo', '陈钰琪'],
  '羊织道（董洁）': ['羊织道', '董洁'],
  '吴昕（伊芙丽）': ['伊芙丽', '吴昕'],
  '杨紫（sam edelman）': ['sam edelman', '杨紫'],
  '陈哲远（ducetica）': ['DUVETICA', '陈哲远'],
  '肖顺尧（ducetica）': ['DUVETICA', '肖顺尧'],
  '曾黎（伊芙丽）': ['伊芙丽', '曾黎'],
  '孙怡（club monaco）': ['club monaco', '孙怡'],
  '周洁琼（诗凡黎）': ['诗凡黎', '周洁琼'],
  '肖战（heurueh）': ['heurueh', '肖战'],
  '杨幂(思加图)': ['思加图', '杨幂'],
  '杨幂（思加图）': ['思加图', '杨幂'],
  '钟楚曦（真美诗）': ['真美诗', '钟楚曦'],
  '孙伊涵duvetica': ['DUVETICA', '孙伊涵'],
  'papi酱（羊织道）': ['羊织道', 'papi酱'],
  '黄雅琼（尚美巴黎）': ['尚美巴黎', '黄雅琼'],
  '高圆圆（尚美巴黎）': ['尚美巴黎', '高圆圆'],
  '此沙（尚美巴黎）': ['尚美巴黎', '此沙'],
  '刘宇宁（宝曼兰朵）': ['宝曼兰朵', '刘宇宁'],
  '董洁（真美诗官宣）': ['真美诗', '董洁 官宣'],
  '宋茜（lily）': ['lily', '宋茜'],
  '杨超越（foreshadow）': ['foreshadow', '杨超越'],
  '徐梦洁（moromoro）': ['moromoro', '徐梦洁'],
  '于文文（诗凡黎）': ['诗凡黎', '于文文'],
  '赵丽颖（de beers）': ['De Beers', '赵丽颖'],
  '周雨彤（OGR）': ['OGR', '周雨彤'],
  '董洁（真美诗）': ['真美诗', '董洁'],
  '董洁（wanatry）': ['wanatry', '董洁'],
  '董洁（羊织道）': ['羊织道', '董洁'],
  '迪丽热巴（alexandre de paris）': ['alexandre de paris', '迪丽热巴'],
  '周也（olens美瞳）': ['olens', '周也 美瞳'],
  '赵露思（poet wong）': ['poet wong', '赵露思'],
  'delvaux包包': ['delvaux', '包包'],
  '周迅姚晨HERSENSES': ['HERSENSES', '周迅 姚晨'],
  '徐璐 ICEWALD': ['ICEWALD', '徐璐'],
  '周洁琼（ideverray）': ['ideverray', '周洁琼'],
  'lost in echo君妍姐': ['lost in echo', '君妍姐'],
  '童瑶（歌力思）': ['歌力思', '童瑶'],
  '丁程鑫（vwl）': ['vwl', '丁程鑫'],
  '吉娜（博士伦）': ['博士伦', '吉娜'],
  'inital（关智斌）': ['initial', '关智斌'],
  '赵露思（alexandre de paris）': ['alexandre de paris', '赵露思'],
  '孔雪儿（ideverray）': ['ideverray', '孔雪儿'],
  '迪丽热巴（海昌隐形眼镜）': ['海昌', '迪丽热巴 隐形眼镜'],
  '赵露思（lost in echo）': ['lost in echo', '赵露思'],
  '小鬼王凯琳（GOST）': ['GOST', '小鬼王凯琳'],
  '赵露思（蕉内）': ['蕉内', '赵露思'],
  '侯明昊ideverray': ['ideverray', '侯明昊'],
  '宋雨琦mardi': ['MARDI', '宋雨琦'],
  '张嘉倪/赵露思（AGATHA）': ['AGATHA', '张嘉倪/赵露思'],
  '陈都灵（伊芙丽）': ['伊芙丽', '陈都灵'],
  '童瑶（AGATHA）': ['AGATHA', '童瑶'],
  '赵露思（思加图）': ['思加图', '赵露思'],
  '邢菲（MIDO）': ['MIDO', '邢菲'],
  '白鹿ZAUO': ['ZAUO', '白鹿'],
  '白鹿（COZY STEPS）': ['COZY STEPS', '白鹿'],
  '檀健次（de beers）': ['De Beers', '檀健次'],
  '茅子俊（skypeople 天空人）': ['skypeople', '茅子俊 天空人'],
  '陈都灵（FERRAGAMO）': ['FERRAGAMO', '陈都灵'],
  '马伯赛（GROTTO）': ['GROTTO', '马伯赛'],
  '白鹿（百丽）': ['百丽', '白鹿'],
  '白鹿（百丽小号）': ['百丽', '白鹿 小号'],
  '文淇（美特斯邦威）': ['美特斯邦威', '文淇'],
  '达芙妮（韩国爱豆）': ['达芙妮', '韩国爱豆'],
  '虞书欣（DAZZLE）': ['DAZZLE', '虞书欣'],
  '张杰（一万李）': ['一万李', '张杰'],
  '田嘉瑞（the vwl）': ['vwl', '田嘉瑞'],
  '王鹤棣（13de marzo）': ['13de marzo', '王鹤棣'],
  '杨紫（Amber Lollipop）': ['Amber Lollipop', '杨紫'],
  '白鹿（viapitti）': ['VIAPITTI', '白鹿'],
  '龚俊（RR）': ['RR', '龚俊'],
  '杨超越（老铺黄金）': ['老铺黄金', '杨超越'],
  '虞书欣（RR）': ['RR', '虞书欣'],
  '孔雪儿/王怡人marc大小号': ['Marc', '孔雪儿/王怡人 大小号'],
  '博主李宁鞋子': ['李宁', '博主鞋子'],
  '刘雨昕MOUSSY': ['MOUSSY', '刘雨昕'],
  'JTB包包': ['JTB', '包包'],
  'NEON.PEACH大包大号': ['NEON.PEACH', '大包大号'],
  'NEON.PEACH大包小号': ['NEON.PEACH', '大包小号'],
  'AR防晒冰袖': ['AR', '防晒冰袖'],
  '小号，10月10日王鹤棣结款，维特健灵结款': ['维特健灵', '王鹤棣'],
  '己舟（袜子）': ['己舟', '袜子'],
  '杨紫（棒球帽）': ['杨紫', '棒球帽'],
  '周雨彤（小众饰品）': ['周雨彤', '小众饰品'],
  '朱珠（闪跌美容仪）': ['朱珠', '闪跌美容仪'],
  '檀健次（雪服）': ['檀健次', '雪服'],
  '瞿颖（于文文的也都结清）': ['瞿颖', '于文文的也都结清'],
  '胡歌（马克杯）': ['胡歌', '马克杯'],
  '朱珠（珠宝）': ['朱珠', '珠宝'],
  '孙珍妮（粉色包包）': ['孙珍妮', '粉色包包'],
  '刘雅瑟（美瞳）': ['刘雅瑟', '美瞳'],
  '周翊然（小狗项链）': ['周翊然', '小狗项链'],
  '郭文滔（包）': ['郭文滔', '包'],
  '朱志鑫（鞋）': ['朱志鑫', '鞋'],
  '于适（冲锋衣）': ['于适', '冲锋衣'],
  '郭晓婷美容仪': ['郭晓婷', '美容仪'],
  '范丞丞卫衣': ['范丞丞', '卫衣'],
  '沈月小衫': ['沈月', '小衫'],
  '蔡少芬上衣': ['蔡少芬', '上衣'],
  '马嘉琪鞋子': ['马嘉琪', '鞋子'],
  '张淼怡包包': ['张淼怡', '包包'],
  '唐诗逸星空裙': ['唐诗逸', '星空裙'],
  '赵露思卫衣': ['赵露思', '卫衣'],
  '张新成短袖': ['张新成', '短袖'],
  '赵露思外套': ['赵露思', '外套'],
  '卢昱晓鞋子': ['卢昱晓', '鞋子'],
  '白百何 娇阳伴我': ['白百何', '娇阳伴我'],
  '杨蓉 耳饰': ['杨蓉', '耳饰'],
  '李一桐周雨彤皮衣': ['李一桐 周雨彤', '皮衣'],
  '周也童瑶连衣裙': ['周也 童瑶', '连衣裙'],
  '唐艺昕，熟年': ['唐艺昕', '熟年'],
  '张予曦防晒衣': ['张予曦', '防晒衣'],
  '古力娜扎防晒衣': ['古力娜扎', '防晒衣'],
  'tf家族面包鞋': ['tf家族', '面包鞋'],
  '三分野 牙刷': ['三分野', '牙刷'],
  '赫莲娜包': ['赫莲娜', '包'],
  'LUSANT露灿': ['露灿', ''],
  'OWEN欧文': ['OWEN', '']
}

const canonicalCases = {
  '73hours': '73Hours',
  '73hourts': '73Hours',
  'acmeitem': 'ACMEITEM',
  'dovetail': 'DOVETAIL',
  'fax': 'FAX',
  'fila': 'FILA',
  'howwell': 'Howwell',
  'marc': 'Marc',
  'oups': 'oups',
  'pedro': 'PEDRO',
  'palavas': 'Palavas',
  'rosahermoso': 'ROSAHERMOSO',
  'zauo': 'ZAUO',
  'wantry': 'wanatry',
  'anta': '安踏',
  '何方': 'HEFANG',
  'mardi': 'MARDI',
  'moussy': 'MOUSSY',
  '冠军': 'champion',
  '爱可米': 'ACMEITEM',
  'njp睡衣': 'NJP',
  'nj睡衣': 'NJP'
}

export function normalizeBrandAndNote(rawBrand, rawNote) {
  let b = String(rawBrand || '').trim()
  let n = String(rawNote || '').trim()

  if (n === b) {
    n = ''
  }

  // Exact match from composite dictionary
  if (exactMap[b]) {
    const [canonicalBrand, noteDetail] = exactMap[b]
    b = canonicalBrand
    if (noteDetail) {
      n = n ? `${n} ${noteDetail}`.trim() : noteDetail
    }
  }

  // Check NJP pajama variants
  if (b.toLowerCase().includes('njp') || b.toLowerCase().includes('nj睡衣')) {
    b = 'NJP'
    n = n ? `${n} 睡衣`.trim() : '睡衣'
  }

  // Case normalization
  const lowerB = b.toLowerCase()
  if (canonicalCases[lowerB]) {
    b = canonicalCases[lowerB]
  } else if (canonicalCases[b]) {
    b = canonicalCases[b]
  }

  return { brand: b, note: n }
}
